name: Build CV PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t resume-builder .

    - name: Run build inside container
      run: docker run --rm -v ${{ github.workspace }}:/cv resume-builder

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: Resume PDF
        path: CV/main.pdf
